// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfmlzpnzqckhpxvgwzzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mbWx6cG56cWNraHB4dmd3enpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzQ2MDIsImV4cCI6MjA2MDk1MDYwMn0.HsZ5wUnDSmYtd9jy0J8fg60-7svvCGX56TJpLD3DPqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);